env:
  es6: true
  node: true
  mocha: true
parser: "@typescript-eslint/parser"
parserOptions:
  sourceType: module
plugins:
  - "@typescript-eslint"

# extends:
#  - "plugin:@typescript-eslint/eslint-recommended"
#  - "plugin:@typescript-eslint/recommended"
rules:
  ## Coding style
  no-nested-ternary: "error"
  quotes: ["error", "single",{ "avoidEscape": true }]
  comma-style: ["error", "last"]
  no-mixed-spaces-and-tabs: "error"
  no-trailing-spaces: "error"
  no-multi-str: "error"
  semi: ["error", "always"]
  ## Error-prone
  eqeqeq: ["error", "smart"]
  no-func-assign: "error"
  no-prototype-builtins: "error"
  no-redeclare: "error"
  no-sequences: "error"
  no-unreachable: "error"
  # no-unused-vars: ["error", {args: "all", rgsIgnorePattern: "^_"}]
  no-unused-vars": "off"
  ? "@typescript-eslint/no-unused-vars"
  : error
